# 数据库信息
db:
  # 数据库 url
  url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
  # 数据库用户名
  username: root
  # 数据库密码
  password: 12345678
  # 生成的数据库的表,以 , 分割，不填则生成所有表
  table: article, role
  # 前缀
  prefix:
    # 设置过滤表前缀
    table: t_
    # 设置过滤字段前缀
    field: t_
  # id 分配方式(IdType.AUTO: auto, IdType.NONE: none, IdType.INPUT: input, IdType.ASSIGN_ID: id, IdType.ASSIGN_UUID: uuid)
  id_type: auto

# 作者信息
author:
  name: Lord Camelot

# 文件信息
file:
  # 输出位置
  output: /Users/lord/Documents/Programmer/idea/Code

# 项目信息
project:
  name: java-demo-mybatis-plus
  # 包名
  package: com.camelot
  # 模块名
  module: